<div class="field choice sarehub">
    <input type="checkbox" name="agree_to_sarehub" title="<?php /* @escapeNotVerified */ echo __('Agree to SAREhub') ?>" value="1" id="agree_to_sarehub" class="checkbox">
    <label for="agree_to_sarehub" class="label"><span><?php /* @escapeNotVerified */ echo __('Agree to SAREhub') ?></span> (<a target="_blank" href="https://sarehub.com/SAREhub_REGULAMIN.pdf"><?php echo __('SAREhub terms and conditions');?></a>)</label>
</div>
